[package]
name = "caduceus"
version = "0.0.1"
edition = "2021"
description = "A software suite for exploring power consumption-based data through Side-Channel Analysis."
license = "Apache-2.0"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3